### ISSUE TITLE
panic on main

### ISSUE THREAD

**Issue by mattn** [fiatjaf/njump#65]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xe1d30f]

goroutine 1 [running]:
main.main()
    /app/main.go:69 +0x1af
```
sys still be nil at main.go:69
sys is instantiated at initSystem()

**Comment by fiatjaf** [comment]
Oops, sorry.
